compatibility_date = "2024-11-08"
name = "fastapi"

[vars]
UPSTASH_REDIS_REST_TOKEN = "AWlNAAIjcDE1MDJmMDMzYjUzZTg0YjU3OGJlMzcwZDQ0N2ZlODhlZXAxMA"
UPSTASH_REDIS_REST_URL = "https://handy-muskox-26957.upstash.io"

# wrangler.toml (wrangler v3.79.0^)
[observability]
enabled = true
head_sampling_rate = 1
