compatibility_date = "2024-11-08"
name = "fastapi"

[vars]
UPSTASH_REDIS_REST_TOKEN = 'https://handy-muskox-26957.upstash.io'
UPSTASH_REDIS_REST_URL = 'AWlNAAIjcDE1MDJmMDMzYjUzZTg0YjU3OGJlMzcwZDQ0N2ZlODhlZXAxMA'
